### ISSUE TITLE
Make Search Component

### ISSUE THREAD

**Issue by phortonssf** [Nara77/Final-Project#6]
Search Component Will
    --- use 2 way binding [(ngModel)] to get data from the view to the service

User Input Data Flow
    HTML INPUT --> Service 
   -- connect search component to service so the input is your search term to your api

**Comment by Nara77** [comment]
There is a search box but data won't display, it compiles successfully and I have no error on the cosnsol, not sure wt the problem is. I know I'm gonna need that data for the movielist.
